# Generated by Django 2.2.24 on 2021-08-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-create',), 'verbose_name_plural': 'Products'},
        ),
    ]
